apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-argocd-model-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gpt-argocd-model
  template:
    metadata:
      labels:
        app: gpt-argocd-model
    spec:
      containers:
      - name: gpt-argocd-model-container
        image: gcr.io/<YOUR_PROJECT_ID>/gpt-argocd-model:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
